Controllers: listNoColaboradoresUTMByCarreraByTesis y updatePrioridadesTestistas
Emanuel-Palestino/ProyectoUTM-Servidor pull request #57
Opened 2022-06-25 20:34 UTC by snifex

<h1>Controllers:</h1>
<h2>updatePrioridadesTestistas</h2>

**Datos originales**
![image](https://user-images.githubusercontent.com/58663377/175789615-9ab641a8-6bd3-46b3-8e51-5cdf86a4555a.png)

**Datos del body**
![image](https://user-images.githubusercontent.com/58663377/175789624-53b07b18-e1ca-4de1-bf6c-b35e90e242e4.png)

**Resultado de la consulta**
![image](https://user-images.githubusercontent.com/58663377/175789651-2af4900f-ab93-41ed-8f1d-b1fb5ea24b47.png)

<h2>listNoColaboradoresUTMByCarreraByTesis</h2>

**Datos en la tabla**
![image](https://user-images.githubusercontent.com/58663377/175789659-e63c34f1-0100-4d39-8d16-1e49f895222a.png)

**Profesores del instituto**
![image](https://user-images.githubusercontent.com/58663377/175789664-eeba9ba7-ec9b-4827-bd22-79c217aac4f6.png)

**Resultado**
![image](https://user-images.githubusercontent.com/58663377/175789669-eae52618-63c0-4487-9d98-0053c5062c83.png)

2022-06-25 20:45 UTC, Emanuel-Palestino requested changes
Corregir

2022-06-25 20:45 UTC, Emanuel-Palestino commented on src/controllers/TesistasController.ts
> +			respuesta = await pool.query('UPDATE profesorYTesis SET ? WHERE idTesis = ? AND idProfesor = ?', [elementoBody,idTesis, elementoBody.idProfesor]);
Te falta una condición, la de esInterno

2022-06-25 21:59 UTC, snifex commented on src/controllers/TesistasController.ts
> +			respuesta = await pool.query('UPDATE profesorYTesis SET ? WHERE idTesis = ? AND idProfesor = ?', [elementoBody,idTesis, elementoBody.idProfesor]);
En la carta no dice nada sobre alguna condicion si es interno o no, con esas condiciones solamente checo a que tesis y a que profesor se le va a asignar, pero ya esta en el commit mas reciente

2022-06-26 04:10 UTC, Emanuel-Palestino requested changes
Corregir

2022-06-26 04:10 UTC, Emanuel-Palestino commented on src/controllers/TesistasController.ts
> +			respuesta = await pool.query('UPDATE profesorYTesis SET ? WHERE idTesis = ? AND idProfesor = ? AND esInterno = 1', [elementoBody,idTesis, elementoBody.idProfesor]);
El valor de esInterno se recibe del body.

2022-06-26 04:14 UTC, snifex commented on src/controllers/TesistasController.ts
> +			respuesta = await pool.query('UPDATE profesorYTesis SET ? WHERE idTesis = ? AND idProfesor = ? AND esInterno = 1', [elementoBody,idTesis, elementoBody.idProfesor]);
Ya esta corregido

2022-06-26 04:17 UTC, merged